### PR TITLE
Won't fix the build but nice catch, so I want to commit anyway

### PR DESCRIPTION
**Pull request by oliviertoupin**
@mlaflamm @alex-wajam

### CODE REVIEW

**Comment by alexbergeron** [comment]
+1 (I prefer the .asScala way too)

**Comment by oliviertoupin** [comment]
It's not that I prefer that way, it's that it will prevent a shit ton of MapWrapper

**Comment by alexbergeron** [comment]
I said it mostly as a bonus.

It's more explicit and just as readable. 

I know I use lots of implicits theses days, but explicit will always be better than implicit

**Comment by alexbergeron** [comment]
(Second line of Zen of Python)

**Pull request merged**
