### PR TITLE
Fix dry mode when using partial updates

### PR DESCRIPTION
**Pull request by alexbergeron**
@mlaflamm @jgagnon1 @appaquet

### CODE REVIEW

**Comment by appaquet** [comment]
Pretty sure we should make more tests with dryMode. There may be other bugs laying around.

+1 from me for the changes though

**Comment by mlaflamm** [comment]
I agree with @appaquet, we can probably make `MysqlStorageFixture.exec()` run once in dry mode followed by the standard mode for all tests. 

+1 for this pull request. I added the story BE-446 for adding extra <b>dry mode</b> tests.

**Comment by alexbergeron** [comment]
I agree that we're missing more integration tests with dry mode, but I have two points I need to make before merging this:
1. I'm not running the actual test that found this bug in dry mode. I should fix this before merging
2. There could be a simpler fix for this issue, possibly in `TableValue`

**Comment by alexbergeron** [comment]
Updated

**Comment by mlaflamm** [comment]
+1

**Pull request merged**
